version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    insecure-external-code-execution: "deny"
    directory: "/"
    schedule:
      interval: "daily"
