services:
  whisper-worker:
    image: whisper-asr-worker:latest
    volumes:
      - ./model:/model
      - ./data:/data
    container_name: whisper-asr-worker
    env_file:
      - .env.override
    logging:
      options:
        max-size: 20m
    restart: no
    ports:
      - "5333:5333"
    
    # Comment below to use the CPU instead of the GPU/CUDA
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - capabilities: [gpu]