name: Build & Push

on:
  push:
    branches:
    -  main
  workflow_call:
  workflow_dispatch:

jobs:
  build-push-image:
    uses: beeldengeluid/gha-workflows/.github/workflows/build-push-image.yml@ec3fa53a64d7cb6be5a435cd11827af7394ee55f # v2026.04.17
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write
