name: Build & Push

on:
  push:
    branches:
    -  main
  workflow_call:
  workflow_dispatch:

jobs:
  build-push-image:
    uses: beeldengeluid/gha-workflows/.github/workflows/build-push-image.yml@ab3c1e9bbad4a10d44dd8f2831b9a0ac5ed84789 # v2026.04.30
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write
