name: Build & Push

on:
  push:
    branches:
    -  main
  workflow_call:
  workflow_dispatch:

jobs:
  build-push-image:
    uses: beeldengeluid/gha-workflows/.github/workflows/build-push-image.yml@1a3052942c2206d7c7145d751c5f750c42d5a035 # v2026.03.05
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write
